### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by Poussinou** [sz3/cfc#11]
Hi,

Since this app is MIT licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind.

You can find some documentation [here](https://f-droid.org/docs/).

Otherwise, if you don't want to work on the inclusion of this app by yourself, would it be ok for you if someone else do it for you?

**Comment by sz3** [comment]
The short answer is: I haven't really looked into it. But I don't think it's a bad idea.

I'm guessing it will take a bit of effort to make the f-droid build process happy. If anyone wants to take a crack at getting the app built in that environment, let me know if it works... and maybe submit a PR here with any necessary changes to the build. :)

**Comment by Poussinou** [comment]
I opened a RFP [here](https://gitlab.com/fdroid/rfp/-/issues/2092).

**Comment by IzzySoft** [comment]
And I contributed Fastlane (the bot complained it was missing – so I bundled what's used in my repo, where your app [is already listed](https://apt.izzysoft.de/fdroid/index/apk/org.cimbar.camerafilecopy). My library scanner (which is also used at F-Droid) found nothing to complain, so consider that check passed already :smiley:

**Comment by sz3** [comment]
PR is merged!

Thanks for the help. Maybe I'll make a contributors file ... :smile:

**Comment by IzzySoft** [comment]
Gladly done! RFP updated as well. Next bot scan results due within an our (hopefully).

**Comment by IzzySoft** [comment]
@sz3 now that your app made it to F-Droid.org, so you still want to keep it in my repo? I usually remove apps at this point given an overlap of about 10 days (which was reached today) unless explicitly requested to keep them. You can find some background, pros & cons [in my wiki](https://gitlab.com/IzzyOnDroid/repo/-/wikis/FAQ) should you need help for your decision.

**Comment by sz3** [comment]
I think it's fine to remove it. Thanks for all the help. :)
