### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [sz3/cfc#20]
https://monitor.f-droid.org/builds/log/org.cimbar.camerafilecopy/9#site-footer

```
> Task :app:stripReleaseDebugSymbols FAILED

FAILURE: Build failed with an exception.

* What went wrong:

Execution failed for task ':app:stripReleaseDebugSymbols'.

> 1 exception was raised by workers:

org.gradle.process.internal.ExecException: A problem occurred starting process 'command '/opt/android-sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/bin/arm-linux-androideabi-strip''
```

Could you please take a look? Thanks!

**Comment by sz3** [comment]
Man, I hate android development.

Thanks for posting this.

**Comment by sz3** [comment]
Ok, for now I rolled back the ndk change on master, which should be sufficient to fix the build (I think).

**Comment by licaon-kter** [comment]
Done https://gitlab.com/fdroid/fdroiddata/-/commit/ae4c6129a42221d7c399e8e904828845dd95c406

**Comment by linsui** [comment]
Thanks!
